Repository woorifisa-projects-3rd/WeKids-BE, pull requests merged in 2024-11, with the labels that each got.

#2 [FEAT] 프로젝트 초기세팅
  .github/ISSUE_TEMPLATE/custom.md
  .github/pull_request_template.md
  .gitignore
  .gitmessage.txt
  src/main/java/com/wekids/backend/exception/ErrorCode.java
  src/main/java/com/wekids/backend/exception/ErrorResponse.java
  src/main/java/com/wekids/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/wekids/backend/exception/ValidErrorResponse.java
  src/main/java/com/wekids/backend/exception/WekidsException.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ feature

#4 [FEAT] 패키지 구조
  src/main/java/com/wekids/backend/account/controller/temp.md
  src/main/java/com/wekids/backend/account/domain/temp.md
  src/main/java/com/wekids/backend/account/dto/temp.md
  src/main/java/com/wekids/backend/account/repository/temp.md
  src/main/java/com/wekids/backend/account/service/temp.md
  src/main/java/com/wekids/backend/accountTransaction/controller/temp.md
  src/main/java/com/wekids/backend/accountTransaction/domain/temp.md
  src/main/java/com/wekids/backend/accountTransaction/dto/temp.md
  src/main/java/com/wekids/backend/accountTransaction/repository/temp.md
  src/main/java/com/wekids/backend/accountTransaction/service/temp.md
  src/main/java/com/wekids/backend/member/controller/temp.md
  src/main/java/com/wekids/backend/member/domain/temp.md
  src/main/java/com/wekids/backend/member/dto/temp.md
  src/main/java/com/wekids/backend/member/repository/temp.md
  src/main/java/com/wekids/backend/member/service/temp.md
Labels: ✨ feature

#14 [FEAT] domain 설정
  src/main/java/com/wekids/backend/WekidsApplication.java
  src/main/java/com/wekids/backend/account/domain/Account.java
  src/main/java/com/wekids/backend/account/domain/enums/AccountDesignType.java
  src/main/java/com/wekids/backend/account/domain/enums/AccountState.java
  src/main/java/com/wekids/backend/account/domain/temp.md
  src/main/java/com/wekids/backend/accountTransaction/domain/AccountTransaction.java
  src/main/java/com/wekids/backend/accountTransaction/domain/enums/TransactionType.java
  src/main/java/com/wekids/backend/accountTransaction/domain/temp.md
  src/main/java/com/wekids/backend/common/entity/BaseTime.java
  src/main/java/com/wekids/backend/member/domain/Child.java
  src/main/java/com/wekids/backend/member/domain/Member.java
  src/main/java/com/wekids/backend/member/domain/Parent.java
  src/main/java/com/wekids/backend/member/domain/enums/MemberState.java
  src/main/java/com/wekids/backend/member/domain/mapping/ParentChild.java
  src/main/java/com/wekids/backend/member/domain/mapping/ParentChildId.java
  src/main/java/com/wekids/backend/member/domain/temp.md
Labels: ✨ feature

#24 [CI] 배포 테스트
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .ebextensions-dev/02-https-redirect.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/com/wekids/backend/aws/HealthController.java
Labels: 👷ci, ✨ feature

#25 [CI] 개발 환경 배포 설정
  .github/workflows/dev_deploy.yml
Labels: 👷ci, ✨ feature

#27 [CI] 개발 인프라 CI/CD 파이프라인 구축
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .ebextensions-dev/02-https-redirect.config
  .github/workflows/dev_deploy.yml
  .gitignore
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/com/wekids/backend/aws/HealthController.java
  src/main/resources/application-dev.yml
Labels: 👷ci, ✨ feature

#31 [REFACT] entity 수정
  src/main/java/com/wekids/backend/design/domain/Design.java
Labels: ♻️ refactor

#38 [FEAT] 거래 상세조회 api 구현
  src/main/java/com/wekids/backend/accountTransaction/controller/AccountTransactionController.java
  src/main/java/com/wekids/backend/accountTransaction/domain/AccountTransaction.java
  src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
  src/main/java/com/wekids/backend/config/SecurityConfig.java
  src/test/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImplTest.java
  src/test/java/com/wekids/backend/support/fixture/AccountTransactionFixture.java
Labels: ✨ feature

#39 [FEAT] post 메모저장 기능
  src/main/java/com/wekids/backend/accountTransaction/controller/AccountTransactionController.java
  src/main/java/com/wekids/backend/accountTransaction/domain/AccountTransaction.java
  src/main/java/com/wekids/backend/accountTransaction/dto/request/UpdateMemoRequest.java
  src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionService.java
  src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
  src/test/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImplTest.java
  src/test/java/com/wekids/backend/support/fixture/AccountTransactionFixture.java
Labels: ✨ feature

#26 [FEAT] 계좌 조회
  build.gradle
  src/main/java/com/wekids/backend/account/controller/AccountController.java
  src/main/java/com/wekids/backend/account/dto/response/AccountResponse.java
  src/main/java/com/wekids/backend/account/dto/response/BaasAccountResponse.java
  src/main/java/com/wekids/backend/account/service/AccountService.java
  src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
  src/main/java/com/wekids/backend/baas/aop/BassExceptionHandlingAspect.java
  src/main/java/com/wekids/backend/baas/aop/BassLogAndHandleException.java
  src/main/java/com/wekids/backend/baas/controller/BassController.java
  src/main/java/com/wekids/backend/baas/dto/request/temp.md
  src/main/java/com/wekids/backend/baas/dto/response/AllAccountResponse.java
  src/main/java/com/wekids/backend/baas/dto/response/BaasAllAccountResponse.java
  src/main/java/com/wekids/backend/baas/dto/result/temp.md
  src/main/java/com/wekids/backend/baas/service/BaasService.java
  src/main/java/com/wekids/backend/baas/service/BassServiceImpl.java
  src/main/java/com/wekids/backend/card/service/CardServiceImpl.java
  src/main/java/com/wekids/backend/config/RestTemplateConfig.java
  src/main/java/com/wekids/backend/exception/ErrorCode.java
  src/main/java/com/wekids/backend/member/domain/Parent.java
  src/test/java/com/wekids/backend/account/repository/AccountRepositoryTest.java
  src/test/java/com/wekids/backend/baas/service/BassServiceTest.java
  src/test/java/com/wekids/backend/support/fixture/ParentFixture.java
Labels: ✨ feature

#42 [FEAT] 부모 계정 조회
  src/main/java/com/wekids/backend/account/repository/AccountRepository.java
  src/main/java/com/wekids/backend/baas/service/BassServiceImpl.java
  src/main/java/com/wekids/backend/design/domain/Design.java
  src/main/java/com/wekids/backend/design/domain/DesignId.java
  src/main/java/com/wekids/backend/design/repository/DesignRepository.java
  src/main/java/com/wekids/backend/exception/ErrorCode.java
  src/main/java/com/wekids/backend/member/controller/MemberController.java
  src/main/java/com/wekids/backend/member/controller/ParentController.java
  src/main/java/com/wekids/backend/member/controller/temp.md
  src/main/java/com/wekids/backend/member/dto/response/ChildResponse.java
  src/main/java/com/wekids/backend/member/dto/response/ParentAccountResponse.java
  src/main/java/com/wekids/backend/member/dto/response/ParentResponse.java
  src/main/java/com/wekids/backend/member/dto/response/temp.md
  src/main/java/com/wekids/backend/member/dto/temp.md
  src/main/java/com/wekids/backend/member/repository/MemberRepository.java
  src/main/java/com/wekids/backend/member/repository/ParentRepository.java
  src/main/java/com/wekids/backend/member/service/MemberService.java
  src/main/java/com/wekids/backend/member/service/MemberServiceImpl.java
  src/main/java/com/wekids/backend/member/service/ParentService.java
  src/main/java/com/wekids/backend/member/service/ParentServiceImpl.java
  src/main/java/com/wekids/backend/member/service/temp.md
  src/test/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImplTest.java
  src/test/java/com/wekids/backend/baas/service/BassServiceTest.java
  src/test/java/com/wekids/backend/member/repository/MemberRepositoryTest.java
  src/test/java/com/wekids/backend/member/service/ParentServiceImplTest.java
  src/test/java/com/wekids/backend/support/fixture/AccountFixture.java
  src/test/java/com/wekids/backend/support/fixture/ChildFixture.java
  src/test/java/com/wekids/backend/support/fixture/DesignFixture.java
  src/test/java/com/wekids/backend/support/fixture/ParentFixture.java
Labels: ✨ feature

#45 [FEAT] 자식 정보 조회
  src/main/java/com/wekids/backend/accountTransaction/repository/AccountTransactionRepository.java
  src/main/java/com/wekids/backend/card/repository/CardRepository.java
  src/main/java/com/wekids/backend/design/domain/Design.java
  src/main/java/com/wekids/backend/design/repository/DesignRepository.java
  src/main/java/com/wekids/backend/member/controller/ChildController.java
  src/main/java/com/wekids/backend/member/domain/Child.java
  src/main/java/com/wekids/backend/member/dto/request/temp.md
  src/main/java/com/wekids/backend/member/dto/result/ChildResult.java
  src/main/java/com/wekids/backend/member/dto/result/temp.md
  src/main/java/com/wekids/backend/member/repository/ChildRepository.java
  src/main/java/com/wekids/backend/member/repository/MemberRepository.java
  src/main/java/com/wekids/backend/member/service/ChildService.java
  src/main/java/com/wekids/backend/member/service/ChildServiceImpl.java
  src/test/java/com/wekids/backend/member/repository/ChildRepositoryTest.java
  src/test/java/com/wekids/backend/member/service/ChildServiceImplTest.java
Labels: ✨ feature

#44 [FEAT] 자식 전 계좌 조회
  src/main/java/com/wekids/backend/account/controller/AccountController.java
  src/main/java/com/wekids/backend/account/dto/response/AccountChildResponse.java
  src/main/java/com/wekids/backend/account/dto/response/temp.md
  src/main/java/com/wekids/backend/account/repository/AccountRepository.java
  src/main/java/com/wekids/backend/account/service/AccountService.java
  src/main/java/com/wekids/backend/account/service/AccountServiceImpl.java
  src/test/java/com/wekids/backend/account/service/AccountServiceTest.java
  src/test/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImplTest.java
Labels: ✨ feature

#46 [FEAT] transactions api (이체 api 구현)
  src/main/java/com/wekids/backend/account/domain/Account.java
  src/main/java/com/wekids/backend/account/repository/AccountRepository.java
  src/main/java/com/wekids/backend/accountTransaction/controller/AccountTransactionController.java
  src/main/java/com/wekids/backend/accountTransaction/domain/AccountTransaction.java
  src/main/java/com/wekids/backend/accountTransaction/dto/request/BaaSTransferRequest.java
  src/main/java/com/wekids/backend/accountTransaction/dto/request/TransactionRequest.java
  src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionService.java
  src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
  src/test/java/com/wekids/backend/accountTransaction/controller/AccountTransactionControllerTest.java
  src/test/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImplTest.java
Labels: ✨ feature

#52 [REFACT] 에러 핸들링 추가 및 에러 코드로 변경
  src/main/java/com/wekids/backend/exception/ErrorCode.java
  src/main/java/com/wekids/backend/exception/ErrorResponse.java
  src/main/java/com/wekids/backend/exception/GlobalExceptionHandler.java
Labels: ✨ feature, ♻️ refactor

#48 [FEAT] 인증/인가
  build.gradle
  src/main/java/com/wekids/backend/account/controller/AccountController.java
  src/main/java/com/wekids/backend/accountTransaction/service/AccountTransactionServiceImpl.java
  src/main/java/com/wekids/backend/auth/controller/AuthArgumentResolver.java
  src/main/java/com/wekids/backend/auth/controller/AuthController.java
  src/main/java/com/wekids/backend/auth/controller/MemberId.java
  src/main/java/com/wekids/backend/auth/dto/request/SignUpRequest.java
  src/main/java/com/wekids/backend/auth/dto/response/CustomOAuth2User.java
  src/main/java/com/wekids/backend/auth/dto/response/NaverResponse.java
  src/main/java/com/wekids/backend/auth/dto/response/OAuth2Response.java
  src/main/java/com/wekids/backend/auth/dto/response/SignUpResponse.java
  src/main/java/com/wekids/backend/auth/enums/LoginState.java
  src/main/java/com/wekids/backend/auth/enums/MemberType.java
  src/main/java/com/wekids/backend/auth/jwt/JWTFilter.java
  src/main/java/com/wekids/backend/auth/jwt/JWTUtil.java
  src/main/java/com/wekids/backend/auth/oauth2/CustomSuccessHandler.java
  src/main/java/com/wekids/backend/auth/service/AuthService.java
  src/main/java/com/wekids/backend/auth/service/AuthServiceImpl.java
  src/main/java/com/wekids/backend/auth/service/CustomOAuth2UserService.java
  src/main/java/com/wekids/backend/card/controller/CardIssueController.java
  src/main/java/com/wekids/backend/card/service/CardIssueService.java
  src/main/java/com/wekids/backend/card/service/CardIssueServiceImpl.java
  src/main/java/com/wekids/backend/config/SecurityConfig.java
  src/main/java/com/wekids/backend/config/WebConfig.java
  src/main/java/com/wekids/backend/design/controller/DesignController.java
  src/main/java/com/wekids/backend/exception/ErrorCode.java
  src/main/java/com/wekids/backend/member/controller/ChildController.java
  src/main/java/com/wekids/backend/member/controller/ParentController.java
  src/main/java/com/wekids/backend/member/domain/Member.java
  src/main/java/com/wekids/backend/member/domain/mapping/ParentChild.java
  src/main/java/com/wekids/backend/member/repository/MemberRepository.java
  src/main/java/com/wekids/backend/member/repository/ParentChildRepository.java
  src/main/java/com/wekids/backend/member/repository/ParentRepository.java
  src/main/resources/data.sql
  src/test/java/com/wekids/backend/auth/service/AuthServiceImplTest.java
  src/test/java/com/wekids/backend/card/service/CardIssueServiceTest.java
  src/test/java/com/wekids/backend/support/fixture/ChildFixture.java
  src/test/java/com/wekids/backend/support/fixture/ParentChildFixture.java
  src/test/java/com/wekids/backend/support/fixture/ParentFixture.java
Labels: ✨ feature

#55 [FIX] 인증/인가 오류 수정
  src/main/java/com/wekids/backend/auth/jwt/JWTFilter.java
  src/main/java/com/wekids/backend/auth/oauth2/CustomSuccessHandler.java
Labels: 🐞bug, 🚨 hotfix
